import type { NextPage } from "next";
import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import { trpc } from "../utils/trpc";
import ToggleThemeBtn from "../components/ToggleThemeBtn/ToggleThemeBtn";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const { data: session } = useSession();
  const { data } = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const examples = trpc.useQuery(["example.getAll"]);

  console.log({ session });
  console.log({ examples });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ToggleThemeBtn />
        {!session ? (
          <button onClick={() => signIn()}>Sign in</button>
        ) : (
          <>
            <h2>Hello {session.user?.email}</h2>
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}
        {data ? <p>{data.greeting}</p> : <p>Loading..</p>}
      </main>
    </>
  );
};

export default Home;
